[project]
name = "llm_projects"
version = "0.1.0"
description = "A repo for my LLM projects
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "ollama",
    "openai",
]
